In [1]:
import numpy as np

In [17]:
a = np.array([1, 2, 5, 4, 3, 6]).reshape((3, 2))
a

array([[1, 2],
       [5, 4],
       [3, 6]])

In [30]:
b = np.array([1, 2, 6, 2]).reshape((2, 2))

In [31]:
a - b

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [21]:
np.linalg.norm(a - b, axis=1)

array([0.        , 4.47213595, 4.47213595])

In [4]:
idx = np.argsort(a)

In [25]:
a ** 2

array([[ 1,  4],
       [25, 16],
       [ 9, 36]])

In [24]:
(a ** 2).sum(axis=1)

array([ 5, 41, 45])

In [32]:
b.dot(a.T)

array([[ 5, 13, 15],
       [10, 38, 30]])

In [29]:
a.T

array([[1, 5, 3],
       [2, 4, 6]])

In [34]:
a = np.array([1, 2, 3])
b = np.array([1, 21, 4])

(a == b).mean()

0.3333333333333333